services:
  service-a:
    build:
      context: ./ServiceA
      dockerfile: application.dockerfile
    container_name: service-a
    environment:
      - APP_NAME=service-a
      - SERVICE_B_URL=http://service-b
      - OPENTELEMETRY_ENDRPOIND=http://otel-collector:4317
    ports:
      - "10001:80"
    labels:
      - "platform=distributed-system-platform"
    networks:
      - platform-network

  service-b:
    build:
      context: ./ServiceB
      dockerfile: application.dockerfile
    container_name: service-b
    environment:
      - APP_NAME=service-b
      - OPENTELEMETRY_ENDRPOIND=http://otel-collector:4317
    ports:
      - "10002:80"
    labels:
      - "platform=distributed-system-platform"
    networks:
      - platform-network

networks:
  platform-network:
    external: true
    name: platform-net
